"""core·运行事件流(平台通用件):轮内工具调用/返回实时落库,前端轮询近实时展示。
每事件一行 INSERT 天然增量;进程外(web)随时可读——追盘不再黑盒。"""
from __future__ import annotations   # 类体 def list 遮蔽内置 list,注解需惰性求值

import json
from datetime import datetime as _dt
from functools import wraps

from trader.core.context import current_run
from trader.core.db import _connect, ensure_once

from contextvars import ContextVar

_current_round: ContextVar[int] = ContextVar("current_round", default=0)


def set_current_round(n: int) -> None:
    _current_round.set(n)


def current_round() -> int:
    return _current_round.get()


class RunEvents:
    """事件登记簿:append 落行,list 读流,latest_round 给 API 找进行中轮。"""

    def __init__(self, schema: str = "public") -> None:
        self.schema = schema
        ensure_once(f"run_events:{schema}", self._init_db)

    def append(self, run_id: int, round_: int, kind: str, tool: str = "", body: str = "") -> None:
        with _connect(self.schema) as conn:
            conn.execute(
                "INSERT INTO run_events(run_id, round, kind, tool, body, created_at)"
                " VALUES(%s,%s,%s,%s,%s,%s)",
                (run_id, round_, kind, tool, (body or "")[:2000],
                 _dt.now().isoformat(timespec="seconds")),
            )

    def list(self, run_id: int, round_: int) -> list[dict]:
        with _connect(self.schema) as conn:
            return conn.execute(
                "SELECT id, round, kind, tool, body, created_at FROM run_events"
                " WHERE run_id=%s AND round=%s ORDER BY id",
                (run_id, round_)).fetchall()

    def latest_round(self, run_id: int) -> int:
        with _connect(self.schema) as conn:
            r = conn.execute("SELECT max(round) AS m FROM run_events WHERE run_id=%s",
                             (run_id,)).fetchone()
        return r["m"] or 0

    def round_open(self, run_id: int, round_: int) -> bool:
        """该轮是否进行中(有 round_start 无 round_end)。"""
        with _connect(self.schema) as conn:
            r = conn.execute(
                "SELECT count(*) FILTER (WHERE kind='round_end') AS ends FROM run_events"
                " WHERE run_id=%s AND round=%s", (run_id, round_)).fetchone()
        return (r["ends"] or 0) == 0

    def failure_runs(self, run_id: int) -> list[dict]:
        """轮内失败事件(round_end 以"中断重试"开头):run 486 事故后轮次列表可见。
        按时间升序返回,连续失败聚成链的活交给 queries(它知道轮次边界)。"""
        with _connect(self.schema) as conn:
            return conn.execute(
                "SELECT round, kind, body, created_at FROM run_events"
                " WHERE run_id=%s AND kind='round_end' AND body LIKE '中断重试%%'"
                " ORDER BY id", (run_id,)).fetchall()

    def _init_db(self) -> None:
        with _connect(self.schema) as conn:
            conn.execute(
                """CREATE TABLE IF NOT EXISTS run_events (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_id INTEGER NOT NULL,
                    round INTEGER NOT NULL,
                    kind TEXT NOT NULL,
                    tool TEXT NOT NULL DEFAULT '',
                    body TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL
                )"""
            )
            conn.execute("CREATE INDEX IF NOT EXISTS run_events_run_round"
                         " ON run_events(run_id, round)")


_default: RunEvents | None = None


def default_events() -> RunEvents:
    global _default
    if _default is None:
        _default = RunEvents()
    return _default


def emit(kind: str, tool: str = "", body: str = "") -> None:
    """便捷写:取当前 context 的 run/round 落一行(无 run 上下文则跳过)。
    观测通道——落库失败(DB 断等)绝不杀业务进程。"""
    rid = current_run()
    rnd = current_round()
    if not rid:
        return
    try:
        default_events().append(rid, rnd, kind, tool, body)
    except Exception:  # noqa: BLE001 —— 事件流挂了可以,进程不能挂
        pass


def instrument(fn):
    """工具包装:调用前后各落一行事件(call/ret),前端实时可见。
    functools.wraps 保留原签名——pydantic_ai 的 schema 推断不受影响。"""
    @wraps(fn)
    def inner(*args, **kwargs):
        emit("call", getattr(fn, "__name__", "?"),
             json.dumps(kwargs, ensure_ascii=False, default=str)[:800])
        try:
            out = fn(*args, **kwargs)
        except Exception as e:  # noqa: BLE001 —— 失败也留痕,再抛给重试机制
            emit("ret", getattr(fn, "__name__", "?"), f"ERROR {type(e).__name__}: {e}"[:800])
            raise
        emit("ret", getattr(fn, "__name__", "?"), str(out)[:2000])
        return out
    return inner
