"""core·组合(P0 定稿):核算单元——实盘/模拟/实验三角色,发号登记 + 实验开局 + 指纹。

由旧 bags+ledgers 合并而来(工作台架构 §3):
- type=main:实盘组合,每(用户×系统)恰一个,净值=履历;存量组合 0=expectation 的实盘
- type=paper:模拟组合(跨天虚拟资金,练手/冷启动验证)
- type=experiment:实验组合(重演某日/A-B,一次性,跑完归档)

实验开局三模式(fork 源=用户默认组合):
- fresh(默认):钱包从初始资金;知识(预期/研究/笔记 + 当日预案 + 全部自选组)从源组合复制
- fork:钱包复制源组合现状(回放历史日=带未来持仓,调用方负责在封面标注)
- fork-as-of D:钱包从源组合 fills 流水折叠重建"截至 D 收盘";知识复制源组合现状
- custom:JSON 指定现金+持仓
"""
import hashlib
import json

from trader.core.context import set_context
from trader.core.db import _connect, ensure_once
from trader.core.ledger import INITIAL_CASH, Wallet

# 跨日知识文档(随实验组合复制);premarket 只复制目标日当天;close 永不复制(未来知识)
KNOWLEDGE_TYPES = ("expectation", "research", "note")

PORTFOLIO_TYPES = ("main", "paper", "experiment")


class Portfolios:
    """组合登记簿:一切 portfolio id 从这里发号;身份/角色/归属一体(顶层表,无向下指针)。"""

    def __init__(self, schema: str = "public") -> None:
        self.schema = schema
        ensure_once(f"portfolios:{schema}", self._init_db)

    # ── 登记 ────────────────────────────────────────────

    def create(self, owner_user: int, ptype: str, system_id: int,
               name: str = "") -> int:
        """发一个新组合号。type=main|paper|experiment;main 的唯一性由部分索引兜底。"""
        from datetime import datetime as _dt

        if ptype not in PORTFOLIO_TYPES:
            raise ValueError(f"组合类型非法:{ptype}(允许 {PORTFOLIO_TYPES})")
        with _connect(self.schema) as conn:
            r = conn.execute(
                "INSERT INTO portfolios(owner_user, system_id, name, type, created_at)"
                " VALUES(%s,%s,%s,%s,%s) RETURNING id",
                (owner_user, system_id, name, ptype,
                 _dt.now().isoformat(timespec="seconds"))).fetchone()
        return r["id"]

    def get(self, portfolio_id: int) -> dict | None:
        with _connect(self.schema) as conn:
            return conn.execute("SELECT * FROM portfolios WHERE id=%s",
                                (portfolio_id,)).fetchone()

    def list(self, owner_user: int) -> list[dict]:
        with _connect(self.schema) as conn:
            return conn.execute(
                "SELECT * FROM portfolios WHERE owner_user=%s ORDER BY id",
                (owner_user,)).fetchall()

    # ── 实盘组合寻址 ────────────────────────────────────

    def main_of(self, user_id: int, system_id: int) -> dict | None:
        """某用户某系统的实盘组合(无则 None)。"""
        with _connect(self.schema) as conn:
            return conn.execute(
                "SELECT * FROM portfolios WHERE owner_user=%s AND system_id=%s"
                " AND type='main'", (user_id, system_id)).fetchone()

    def ensure_main(self, user_id: int, system_id: int) -> int:
        """实盘组合:有则返回,无则建(仅实盘组合允许这样兜底,模拟/实验显式开)。"""
        row = self.main_of(user_id, system_id)
        if row:
            return row["id"]
        portfolio_id = self.create(user_id, "main", system_id, name="主组合")
        Wallet(self.schema).open_wallet(INITIAL_CASH, INITIAL_CASH, portfolio_id)
        return portfolio_id

    def ensure_paper(self, user_id: int, system_id: int) -> int:
        """系统的默认模拟组合；允许另建多个，但统一启动器复用最早一个。"""
        with _connect(self.schema) as conn:
            row = conn.execute(
                "SELECT id FROM portfolios WHERE owner_user=%s AND system_id=%s"
                " AND type='paper' ORDER BY id LIMIT 1", (user_id, system_id)).fetchone()
        if row:
            return row["id"]
        portfolio_id = self.create(user_id, "paper", system_id, name="模拟组合")
        Wallet(self.schema).open_wallet(INITIAL_CASH, INITIAL_CASH, portfolio_id)
        return portfolio_id

    def default_for(self, user_id: int) -> int:
        """用户默认组合:第一个实盘组合;没有则 0(兼容旧 default_bag 语义)。"""
        with _connect(self.schema) as conn:
            row = conn.execute(
                "SELECT id FROM portfolios WHERE owner_user=%s AND type='main'"
                " ORDER BY id LIMIT 1", (user_id,)).fetchone()
        return row["id"] if row else 0

    # ── 生命周期 ────────────────────────────────────────

    def delete(self, portfolio_id: int) -> None:
        """销毁组合(行级,一个事务):业务数据 + 版本 + 钱包全清。"""
        with _connect(self.schema) as conn:
            for tbl in ("documents", "watchlist_members", "watchlists", "versions",
                        "positions", "fills"):
                conn.execute(f"DELETE FROM {tbl} WHERE portfolio_id=%s", (portfolio_id,))
            conn.execute("DELETE FROM wallets WHERE portfolio_id=%s", (portfolio_id,))
            conn.execute("DELETE FROM portfolios WHERE id=%s", (portfolio_id,))

    def _init_db(self) -> None:
        with _connect(self.schema) as conn:
            conn.execute(
                """CREATE TABLE IF NOT EXISTS portfolios (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    owner_user INTEGER NOT NULL DEFAULT 0,
                    system_id INTEGER NOT NULL DEFAULT 0,
                    name TEXT NOT NULL DEFAULT '',
                    type TEXT NOT NULL CHECK (type IN ('main','paper','experiment')),
                    broker_account_id INTEGER,
                    created_at TEXT NOT NULL
                )""")
            # 实盘组合每(用户×系统)恰一个——数据库兜底
            conn.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS portfolios_main_unique"
                " ON portfolios(owner_user, system_id) WHERE type='main'")


# ── 开局(执行前绑定组合)──────────────────────────────

def open_live(run_id: int, portfolio_id: int, user_id: int) -> None:
    """实时时钟场:上下文切到发起时绑定的主组合或模拟组合。"""
    set_context(portfolio_id, run_id, user_id)


def open_experiment(portfolio_id: int, date: str, mode: str = "fresh",
                    custom: dict | None = None, as_of: str = "",
                    user_id: int = 0, source_portfolio: int = 0,
                    run_id: int | None = None) -> str:
    """实验组合开局:建钱包 + 从源组合复制知识,切上下文。返回全状态指纹。"""
    acct = Wallet()
    # ① 钱包
    if mode == "fresh":
        acct.open_wallet(INITIAL_CASH, INITIAL_CASH, portfolio_id)
    elif mode == "fork":
        _copy_wallet(acct, portfolio_id, source_portfolio)
    elif mode == "fork-as-of":
        _wallet_as_of(acct, portfolio_id, as_of or date, source_portfolio)
    elif mode == "custom":
        c = custom or {}
        cash = round(float(c.get("cash", 0)) * 100)
        acct.open_wallet(cash, max(cash, 1), portfolio_id)
        with _connect() as conn:
            for p in c.get("positions", []):
                conn.execute(
                    "INSERT INTO positions(portfolio_id, code, name, quantity, sellable,"
                    " avg_cost_cents, bought_on) VALUES(%s,%s,%s,%s,%s,%s,%s)",
                    (portfolio_id, p["code"], p.get("name", ""), int(p["quantity"]),
                     0 if p.get("bought_on") == date else int(p["quantity"]),
                     round(float(p["avg_cost"]) * 100), p.get("bought_on", date)),
                )
    else:
        raise ValueError(f"未知开局模式:{mode}")
    # ② 知识复制(所有模式同规则:从源组合全量 + 当日预案 + 全部自选组)
    _copy_knowledge(portfolio_id, date, source_portfolio)
    set_context(portfolio_id, run_id, user_id)
    return fingerprint(portfolio_id)


def fingerprint(portfolio_id: int) -> str:
    """全状态指纹:现金+持仓+知识文档+自选组的规范化哈希(对比页校验起点一致)。"""
    with _connect() as conn:
        wallet = conn.execute(
            "SELECT cash_cents FROM wallets WHERE portfolio_id=%s", (portfolio_id,)).fetchone()
        positions = conn.execute(
            "SELECT code, quantity, avg_cost_cents FROM positions"
            " WHERE portfolio_id=%s AND quantity>0 ORDER BY code", (portfolio_id,)).fetchall()
        docs = conn.execute(
            "SELECT doc_type, COALESCE(name,'') AS name, COALESCE(trade_date,'') AS d,"
            " meta, md5(content) AS chash FROM documents WHERE portfolio_id=%s"
            " ORDER BY doc_type, name, d", (portfolio_id,)).fetchall()
        wls = conn.execute(
            "SELECT w.name, m.code, m.fields FROM watchlists w"
            " JOIN watchlist_members m ON m.portfolio_id=w.portfolio_id"
            " AND m.list_name=w.name"
            " WHERE w.portfolio_id=%s ORDER BY w.name, m.code", (portfolio_id,)).fetchall()
    norm = {
        "cash": wallet["cash_cents"] if wallet else None,
        "positions": [[p["code"], p["quantity"], p["avg_cost_cents"]] for p in positions],
        "docs": [[d["doc_type"], d["name"], d["d"], json.dumps(d["meta"], sort_keys=True), d["chash"]]
                 for d in docs],
        "watchlists": [[w["name"], w["code"], json.dumps(w["fields"], sort_keys=True)] for w in wls],
    }
    return hashlib.sha256(json.dumps(norm, sort_keys=True, ensure_ascii=False).encode()).hexdigest()[:16]


# ── 内部 ────────────────────────────────────────────────

def _copy_wallet(acct: Wallet, portfolio_id: int, source_portfolio: int = 0) -> None:
    """fork:现金/持仓/流水(含历史)原样复制源组合。"""
    with _connect() as conn:
        src = conn.execute(
            "SELECT cash_cents, initial_cents FROM wallets WHERE portfolio_id=%s",
            (source_portfolio,)).fetchone()
        if src is None:
            raise ValueError(f"源组合 {source_portfolio} 钱包不存在(先跑一次 live 或 migration)")
        acct.open_wallet(src["cash_cents"], src["initial_cents"], portfolio_id)
        conn.execute(
            "INSERT INTO positions(portfolio_id, code, name, quantity, sellable,"
            " avg_cost_cents, bought_on)"
            " SELECT %s, code, name, quantity, sellable, avg_cost_cents, bought_on"
            " FROM positions WHERE portfolio_id=%s", (portfolio_id, source_portfolio))
        conn.execute(
            "INSERT INTO fills(portfolio_id, run_id, code, side, quantity, price_cents,"
            " cash_before_cents, cash_after_cents, position_before, position_after,"
            " created_at, reason, name, trade_time)"
            " SELECT %s, run_id, code, side, quantity, price_cents, cash_before_cents,"
            " cash_after_cents, position_before, position_after, created_at, reason,"
            " name, trade_time FROM fills WHERE portfolio_id=%s", (portfolio_id, source_portfolio))


def _wallet_as_of(acct: Wallet, portfolio_id: int, as_of: str, source_portfolio: int = 0) -> None:
    """fork-as-of:从源组合流水折叠出截至 as_of 收盘的钱包(现金/持仓/T+1)。"""
    d = as_of.replace("-", "")
    iso = f"{d[:4]}-{d[4:6]}-{d[6:8]}"
    with _connect() as conn:
        initial = conn.execute(
            "SELECT initial_cents FROM wallets WHERE portfolio_id=%s",
            (source_portfolio,)).fetchone()["initial_cents"]
        fills = conn.execute(
            "SELECT * FROM fills WHERE portfolio_id=%s ORDER BY id",
            (source_portfolio,)).fetchall()
    cash, pos = initial, {}   # code → {qty, cost_cents(total), bought_on}
    for f in fills:
        ts = (f["trade_time"] or f["created_at"] or "")[:10]
        if ts > iso:
            continue
        code, qty, price_c = f["code"], f["quantity"], f["price_cents"]
        if f["side"] == "BUY":
            p = pos.setdefault(code, {"qty": 0, "cost": 0, "bought_on": f["created_at"][:10]})
            p["qty"] += qty
            p["cost"] += qty * price_c
        else:
            p = pos.get(code)
            if not p:
                continue
            avg = p["cost"] // p["qty"] if p["qty"] else 0
            p["qty"] -= qty
            p["cost"] -= qty * avg
            cash += qty * price_c
            if p["qty"] == 0:
                pos.pop(code)
                continue
        if f["side"] == "BUY":
            cash -= qty * price_c
    acct.open_wallet(cash, initial, portfolio_id)
    with _connect() as conn:
        for code, p in pos.items():
            if p["qty"] <= 0:
                continue
            avg = p["cost"] // p["qty"]
            conn.execute(
                "INSERT INTO positions(portfolio_id, code, name, quantity, sellable,"
                " avg_cost_cents, bought_on) VALUES(%s,%s,%s,%s,%s,%s,%s)",
                (portfolio_id, code, "", p["qty"],
                 p["qty"] if p["bought_on"] < iso else 0, avg, p["bought_on"]),
            )


def _copy_knowledge(portfolio_id: int, date: str, source_portfolio: int = 0) -> None:
    """知识随组合:从源组合全量知识文档 + 目标日预案 + 全部自选组。"""
    with _connect() as conn:
        marks = ",".join(["%s"] * len(KNOWLEDGE_TYPES))
        n = conn.execute(
            f"INSERT INTO documents(doc_type,name,trade_date,content,"
            f" created_at,updated_at,meta,portfolio_id,user_id)"
            f" SELECT doc_type,name,trade_date,content,created_at,updated_at,meta,%s,user_id"
            f" FROM documents WHERE portfolio_id=%s AND (doc_type IN ({marks})"
            f" OR (doc_type='premarket' AND COALESCE(trade_date,'')=%s))",
            (portfolio_id, source_portfolio, *KNOWLEDGE_TYPES, date)).rowcount
        conn.execute(
            "INSERT INTO watchlists(portfolio_id, name, created_at, updated_at, user_id)"
            " SELECT %s, name, created_at, updated_at, user_id FROM watchlists"
            " WHERE portfolio_id=%s", (portfolio_id, source_portfolio))
        conn.execute(
            "INSERT INTO watchlist_members(portfolio_id, list_name, code, name, fields,"
            " updated_at, user_id)"
            " SELECT %s, list_name, code, name, fields, updated_at, user_id"
            " FROM watchlist_members WHERE portfolio_id=%s", (portfolio_id, source_portfolio))
    return n


# ── 单例 ────────────────────────────────────────────────

_portfolios: Portfolios | None = None


def default_portfolios() -> Portfolios:
    global _portfolios
    if _portfolios is None:
        _portfolios = Portfolios()
    return _portfolios
