"""core·prompt 版本库(平台通用件):prompt 内容正本,运行时从这里读。

本地 md 只是临时编辑面:编辑 → sync 入库(同 hash 跳过);md 最终退役(附录 8)。
"""
from trader.core.db import _connect


class PromptVersions:
    """prompt 版本管理:同 hash 不重复入库,变了才存新版本。"""

    def __init__(self, schema: str = "public") -> None:
        self.schema = schema
        self._init_db()

    def save(self, name: str, content: str) -> dict:
        """存入一版(内容未变则跳过)。返回 {name, version, changed, id}。"""
        import hashlib
        from datetime import datetime as _dt

        h = hashlib.sha256(content.encode()).hexdigest()
        with _connect(self.schema) as conn:
            row = conn.execute(
                "SELECT id, version, sha256 FROM prompt_versions"
                " WHERE name=%s ORDER BY version DESC LIMIT 1", (name,)
            ).fetchone()
            if row and row["sha256"] == h:
                return {"name": name, "version": row["version"], "changed": False, "id": row["id"]}
            r = conn.execute(
                "INSERT INTO prompt_versions(name, version, content, sha256, created_at)"
                " VALUES(%s,%s,%s,%s,%s) RETURNING id",
                (name, (row["version"] + 1) if row else 1, content, h,
                 _dt.now().isoformat(timespec="seconds")),
            ).fetchone()
            return {"name": name, "version": (row["version"] + 1) if row else 1,
                    "changed": True, "id": r["id"]}

    def latest(self, name: str) -> str | None:
        """取某 prompt 最新版全文(运行时加载入口)。无则 None。"""
        with _connect(self.schema) as conn:
            row = conn.execute(
                "SELECT content FROM prompt_versions WHERE name=%s"
                " ORDER BY version DESC LIMIT 1", (name,)
            ).fetchone()
        return row["content"] if row else None

    def versions(self, name: str | None = None) -> list[dict]:
        """版本列表(倒序);name 为空列全部 prompt 的最新一版。"""
        with _connect(self.schema) as conn:
            if name:
                return conn.execute(
                    "SELECT id, name, version, sha256, LENGTH(content) AS size, created_at"
                    " FROM prompt_versions WHERE name=%s ORDER BY version DESC", (name,)
                ).fetchall()
            return conn.execute(
                "SELECT DISTINCT ON (name) id, name, version, sha256,"
                " LENGTH(content) AS size, created_at"
                " FROM prompt_versions ORDER BY name, version DESC"
            ).fetchall()

    def get(self, name: str, version: int) -> str | None:
        """取某版全文。"""
        with _connect(self.schema) as conn:
            row = conn.execute(
                "SELECT content FROM prompt_versions WHERE name=%s AND version=%s",
                (name, version),
            ).fetchone()
        return row["content"] if row else None

    def _init_db(self) -> None:
        with _connect(self.schema) as conn:
            conn.execute(
                """CREATE TABLE IF NOT EXISTS prompt_versions (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    version INTEGER NOT NULL,
                    content TEXT NOT NULL,
                    sha256 TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    UNIQUE (name, version)
                )"""
            )
