"""core·交易系统注册表(平台通用件):系统定义正本,manifest 纯数据(实现设计 §3)。

一行 = 一个交易系统。engine 读它装配阶段/工具/prompt;换系统 = 换一行,不改代码。
"""
import json

from trader.core.db import _connect

# expectation 系统的初始 manifest(C2 engine 消费;C3 时从工具白名单里删掉 knowledge 六件)
EXPECTATION_MANIFEST = {
    "system_prompt": "system",
    "stages": {
        "premarket": {"kind": "single", "prompt": "premarket", "request_limit": 200,
                      "vars": ["date", "prev", "weekday", "gap"]},
        "live": {"kind": "loop", "prompt": "round_live", "request_limit": 50,
                 "data_mode": "live", "clock": "real", "window": "09:35-15:05",
                 "skip_lunch": True, "log_type": "watch_live"},
        "replay": {"kind": "loop", "prompt": "round_replay", "request_limit": 50,
                   "data_mode": "replay", "clock": "simulated", "interval": 5,
                   "window": "09:35-15:00", "skip_lunch": True, "log_type": "watch_replay"},
        "close": {"kind": "single", "prompt": "close", "request_limit": 200,
                  "vars": ["date"]},
        "research": {"kind": "single", "prompt": "research", "request_limit": 200,
                     "vars": ["topic"]},
    },
    "tools": [
        # 行情 10
        "get_quotes", "get_indices", "get_kline", "get_block_rank", "get_block_members",
        "get_candidates", "get_limit_up", "get_market_summary", "get_top_amount",
        "get_us_market",
        # 账户与交易
        "get_positions", "get_account", "get_trades", "execute",
        # 看盘组合
        "scan_market",
        # 文档与自选组(平台通用记忆;预期库=expectation 文档+自选组约定)
        "save_doc", "get_doc", "list_docs", "set_doc_meta",
        "save_watchlist", "get_watchlist", "get_watchlist_quotes", "remove_watchlist_member",
    ],
    "web_search": True,
}


class Systems:
    """交易系统注册表:manifest 按名字登记,engine 启动时读取装配。"""

    def __init__(self, schema: str = "public") -> None:
        self.schema = schema
        from trader.core.db import ensure_once
        ensure_once(f"systems:{schema}", self._init_db)

    def upsert(self, name: str, manifest: dict, status: str = "active",
               user_id: int = 0) -> dict:
        """写入/更新一个系统定义(按 user+name 覆盖)。返回该行。"""
        from datetime import datetime as _dt

        now = _dt.now().isoformat(timespec="seconds")
        with _connect(self.schema) as conn:
            row = conn.execute(
                "INSERT INTO systems(user_id, name, manifest, status, created_at, updated_at)"
                " VALUES(%s,%s,%s,%s,%s,%s)"
                " ON CONFLICT (user_id, name) DO UPDATE SET manifest=excluded.manifest,"
                " status=excluded.status, updated_at=excluded.updated_at"
                " RETURNING *",
                (user_id, name, json.dumps(manifest, ensure_ascii=False), status, now, now),
            ).fetchone()
        return row

    def get(self, name: str, user_id: int = 0) -> dict | None:
        """取某系统(manifest 已解析为 dict)。无则 None。"""
        with _connect(self.schema) as conn:
            row = conn.execute("SELECT * FROM systems WHERE user_id=%s AND name=%s",
                               (user_id, name)).fetchone()
        if row:
            row = dict(row)
            if isinstance(row["manifest"], str):  # JSONB 驱动已解析,兼容手插的字符串
                row["manifest"] = json.loads(row["manifest"])
        return row

    def list(self, user_id: int | None = None) -> list[dict]:
        where, args = ("", []) if user_id is None else ("WHERE user_id=%s", [user_id])
        with _connect(self.schema) as conn:
            return conn.execute(
                "SELECT id, user_id, name, manifest, status, created_at, updated_at FROM systems"
                f" {where} ORDER BY id", args
            ).fetchall()

    def _init_db(self) -> None:
        with _connect(self.schema) as conn:
            conn.execute(
                """CREATE TABLE IF NOT EXISTS systems (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    manifest JSONB NOT NULL,
                    status TEXT NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active','archived')),
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                )"""
            )
            # 多租户命名空间(多用户设计 §4-4):user 维度唯一,老全局约束退役
            conn.execute("ALTER TABLE systems ADD COLUMN IF NOT EXISTS user_id INTEGER NOT NULL DEFAULT 0")
            conn.execute("ALTER TABLE systems DROP CONSTRAINT IF EXISTS systems_name_key")
            conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS systems_user_name ON systems(user_id, name)")


_systems: Systems | None = None


def default_systems() -> Systems:
    global _systems
    if _systems is None:
        _systems = Systems()
    return _systems


def ensure_expectation_system(user_id: int = 0) -> dict:
    """确保 expectation 系统已登记(幂等,manifest 以代码里的初始定义为准)。"""
    return default_systems().upsert("expectation", EXPECTATION_MANIFEST, user_id=user_id)
