"""P0 地基迁移(一次性,幂等可重跑):工作台架构 §6 第①-⑥项。

①bags→portfolios(bag_id→portfolio_id,ledgers 合并退役,ref_id 删除)
②portfolios 加 type 三值/system_id/broker_account_id + main 部分唯一索引
③prompt 拆两表(prompts 身份 + prompt_versions.prompt_id)
④runs 加 clock/clock_date/system_id,kind 回填,name→slug
⑤systems.name→slug + display_name 上提为列 + manifest 清理(data_mode/clock 退役)
⑥数据卫生(孤儿实验组合回收、user 3 自动化测试数据清理)

用法:
  uv run python scripts/migrate_p0.py           # 执行
  uv run python scripts/migrate_p0.py --check   # 只读体检,不改数据
"""
import json
import sys

import psycopg

DSN = "host=localhost port=5432 dbname=trader user=postgres password=password"


def q(cur, sql, args=()):
    cur.execute(sql, args)
    try:
        return cur.fetchall()
    except Exception:  # noqa: BLE001 —— DELETE/UPDATE 无结果集
        return []


def table_exists(cur, name: str) -> bool:
    return bool(q(cur, "SELECT 1 FROM information_schema.tables"
                      " WHERE table_schema='public' AND table_name=%s", (name,)))


def col_exists(cur, table: str, col: str) -> bool:
    return bool(q(cur, "SELECT 1 FROM information_schema.columns"
                       " WHERE table_schema='public' AND table_name=%s AND column_name=%s",
                  (table, col)))


# ── ⑥ 数据卫生(先做,在旧表结构上最顺手)────────────────

def hygiene(cur, check: bool) -> None:
    # user 3 = 自动化测试账号(L+随机数账本 ×31 / guard-* 系统 ×19 / bag ×33,0 场次)
    rows = q(cur, "SELECT id FROM bags WHERE owner_user=3")
    bag_ids = [r[0] for r in rows]
    if bag_ids:
        marks = ",".join(["%s"] * len(bag_ids))
        for tbl in ("documents", "watchlist_members", "watchlists", "versions",
                    "positions", "fills", "wallets"):
            n = q(cur, f"DELETE FROM {tbl} WHERE bag_id IN ({marks})", bag_ids)
            print(f"  user3 {tbl}: 删 {cur.rowcount} 行" if not check else f"  [check] user3 {tbl} 将删")
        q(cur, "DELETE FROM bags WHERE owner_user=3")
        print(f"  user3 bags: 删 {len(bag_ids)}")
    q(cur, "DELETE FROM ledgers WHERE user_id=3")
    q(cur, "DELETE FROM systems WHERE user_id=3")
    print("  user3 ledgers/systems: 清除")

    # 孤儿实验组合:ephemeral 但 ref_id 指向的场次已不存在
    orphans = q(cur, "SELECT b.id FROM bags b LEFT JOIN runs r ON r.id=b.ref_id"
                     " WHERE b.kind='ephemeral' AND b.ref_id IS NOT NULL AND r.id IS NULL")
    for (bid,) in orphans:
        print(f"  孤儿实验组合 bag {bid}: 回收")
        for tbl in ("documents", "watchlist_members", "watchlists", "versions",
                    "positions", "fills", "wallets"):
            q(cur, f"DELETE FROM {tbl} WHERE bag_id=%s", (bid,))
        q(cur, "DELETE FROM bags WHERE id=%s", (bid,))


# ── ①② bags+ledgers → portfolios ───────────────────────

def migrate_portfolios(cur, check: bool) -> None:
    if table_exists(cur, "portfolios"):
        print("  portfolios 已存在,跳过")
        return
    # 每用户的"主系统"(组合挂靠):该用户 id 最小的系统;无系统则 expectation
    systems = {r[0]: r[1] for r in q(cur, "SELECT user_id, min(id) FROM systems GROUP BY user_id")}
    exp = q(cur, "SELECT id FROM systems WHERE slug='expectation' AND user_id=0"
             if col_exists(cur, "systems", "slug") else
             "SELECT id FROM systems WHERE name='expectation' AND user_id=0")
    exp_id = exp[0][0] if exp else 1
    primary_system = lambda uid: systems.get(uid, exp_id)   # noqa: E731

    cur.execute("""CREATE TABLE portfolios (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        owner_user INTEGER NOT NULL DEFAULT 0,
        system_id INTEGER NOT NULL DEFAULT 0,
        name TEXT NOT NULL DEFAULT '',
        type TEXT NOT NULL CHECK (type IN ('main','paper','experiment')),
        broker_account_id INTEGER,
        created_at TEXT NOT NULL
    )""")
    # 序列对齐存量最大 id(手工建表带历史行时 identity 序列默认从头)
    cur.execute("SELECT setval(pg_get_serial_sequence('portfolios','id'),"
                " COALESCE((SELECT max(id) FROM portfolios), 1))")
    # 实验组合的归属:ref_id 指向的场次所在系统
    run_system = {}
    sys_by_name = {(r[0], r[1]): r[2] for r in q(
        cur, "SELECT user_id, name, id FROM systems")}
    for uid, sname, sid in q(cur, "SELECT user_id, system, system_id FROM runs"
                             if col_exists(cur, "runs", "system_id") else
                             "SELECT user_id, system, 0 FROM runs"):
        run_system[sname] = sys_by_name.get((uid, sname), primary_system(uid))

    # 持久组合:ledgers(live→main / paper→paper)
    n_main = n_paper = 0
    for l in q(cur, "SELECT l.user_id, l.name, l.kind, l.bag_id, b.created_at"
                    " FROM ledgers l JOIN bags b ON b.id=l.bag_id"):
        ptype = "main" if l[2] == "live" else "paper"
        sid = primary_system(l[0])
        cur.execute("INSERT INTO portfolios(id,owner_user,system_id,name,type,created_at)"
                    " VALUES(%s,%s,%s,%s,%s,%s)",
                    (l[3], l[0], sid, l[1], ptype, l[4] or ""))
        n_main += ptype == "main"
        n_paper += ptype == "paper"
    # 实验组合:ephemeral(无 ledgers 行)
    n_exp = 0
    for b in q(cur, "SELECT id, owner_user, ref_id, created_at FROM bags WHERE kind='ephemeral'"):
        sid = run_system.get(q(cur, "SELECT system FROM runs WHERE id=%s", (b[2],))[0][0],
                             primary_system(b[1])) if b[2] else primary_system(b[1])
        cur.execute("INSERT INTO portfolios(id,owner_user,system_id,name,type,created_at)"
                    " VALUES(%s,%s,%s,%s,'experiment',%s)",
                    (b[0], b[1], sid, "", b[3] or ""))
        n_exp += 1
    # 兜底:有 bags 行但两边都没覆盖的持久袋(理论上没有)→ paper
    for b in q(cur, "SELECT id, owner_user, created_at FROM bags WHERE kind='persistent'"
                    " AND id NOT IN (SELECT id FROM portfolios)"):
        cur.execute("INSERT INTO portfolios(id,owner_user,system_id,name,type,created_at)"
                    " VALUES(%s,%s,%s,'','paper',%s)",
                    (b[0], b[1], primary_system(b[1]), b[2] or ""))
        n_paper += 1
    print(f"  portfolios: main×{n_main} paper×{n_paper} experiment×{n_exp}")

    # 全库列名:bag_id → portfolio_id(约束/索引定义自动跟随)
    for tbl in ("runs", "documents", "watchlists", "watchlist_members",
                "positions", "fills", "wallets", "versions"):
        if col_exists(cur, tbl, "bag_id"):
            cur.execute(f"ALTER TABLE {tbl} RENAME COLUMN bag_id TO portfolio_id")
    cur.execute("DROP TABLE IF EXISTS bags")
    cur.execute("DROP TABLE IF EXISTS ledgers")
    # 索引名归位(纯观感,定义已随列名更新)
    for old, new in (("fills_bag", "fills_portfolio"), ("positions_bag", "positions_portfolio"),
                     ("positions_bag_code", "positions_portfolio_code"),
                     ("documents_bag", "documents_portfolio"), ("versions_bag", "versions_portfolio")):
        cur.execute(f"ALTER INDEX IF EXISTS {old} RENAME TO {new}")


# ── ⑤ systems:name→slug + display_name 上提 + manifest 清理 ──

def migrate_systems(cur, check: bool) -> None:
    if col_exists(cur, "systems", "slug"):
        print("  systems.slug 已存在,跳过")
    else:
        cur.execute("ALTER TABLE systems ADD COLUMN IF NOT EXISTS display_name TEXT NOT NULL DEFAULT ''")
        # display_name 从 manifest 上提;manifest 清理(display_name/stage 级 data_mode/clock)
        for sid, name, manifest in q(cur, "SELECT id, name, manifest FROM systems"):
            m = manifest if isinstance(manifest, dict) else json.loads(manifest)
            display = m.pop("display_name", None) or name
            stages = {}
            for st, sdef in (m.get("stages") or {}).items():
                sdef = {k: v for k, v in sdef.items() if k not in ("data_mode", "clock")}
                stages[st] = sdef
            m["stages"] = stages
            m.setdefault("doc_classes", {"library": ["expectation", "research", "note"],
                                         "ephemeral": ["premarket", "close"]})
            cur.execute("UPDATE systems SET display_name=%s, manifest=%s WHERE id=%s",
                        (display, json.dumps(m, ensure_ascii=False), sid))
        cur.execute("ALTER TABLE systems RENAME COLUMN name TO slug")
        cur.execute("ALTER INDEX IF EXISTS systems_user_name RENAME TO systems_user_slug")
        print("  systems: name→slug + display_name 上提 + manifest 清理完成")


# ── ④ runs:name→slug + clock/system_id 回填 ─────────────

def migrate_runs(cur, check: bool) -> None:
    if col_exists(cur, "runs", "slug"):
        print("  runs.slug 已存在,跳过")
    else:
        cur.execute("ALTER TABLE runs ADD COLUMN IF NOT EXISTS clock TEXT NOT NULL DEFAULT 'real'")
        cur.execute("ALTER TABLE runs ADD COLUMN IF NOT EXISTS clock_date TEXT")
        cur.execute("ALTER TABLE runs ADD COLUMN IF NOT EXISTS system_id INTEGER NOT NULL DEFAULT 1")
        # kind → clock 回填(replay=模拟时钟+重演日)
        cur.execute("UPDATE runs SET clock='simulated', clock_date=trade_date WHERE kind='replay'")
        # system 文字 → system_id(按 user+slug 关联 systems)
        cur.execute("""UPDATE runs r SET system_id = s.id FROM systems s
                       WHERE s.user_id = r.user_id AND s.slug = r.system""")
        # 未命中的回填补主系统
        cur.execute("""UPDATE runs r SET system_id = COALESCE(
                         (SELECT min(s.id) FROM systems s WHERE s.user_id = r.user_id), 1)
                       WHERE r.system_id = 1 AND r.user_id != 0""")
        cur.execute("ALTER TABLE runs RENAME COLUMN name TO slug")
        cur.execute("ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_kind_check")  # kind 转推导
        cur.execute("ALTER TABLE runs DROP COLUMN IF EXISTS schema_name")           # 旧 schema 回放遗留
        cur.execute("DROP INDEX IF EXISTS runs_user_name")
        cur.execute("CREATE UNIQUE INDEX IF NOT EXISTS runs_user_slug ON runs(user_id, slug)")
        print("  runs: name→slug + clock/clock_date/system_id 回填完成")


# ── ③ prompt 拆两表 ────────────────────────────────────

def migrate_prompts(cur, check: bool) -> None:
    if table_exists(cur, "prompts"):
        print("  prompts 已存在,跳过")
        return
    cur.execute("""CREATE TABLE prompts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        system_id INTEGER,
        user_id INTEGER NOT NULL DEFAULT 0,
        slug TEXT NOT NULL,
        display_name TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL
    )""")
    cur.execute("CREATE UNIQUE INDEX prompts_system_slug ON prompts(system_id, slug)"
                " WHERE system_id IS NOT NULL")
    cur.execute("CREATE UNIQUE INDEX prompts_user_slug ON prompts(user_id, slug)"
                " WHERE system_id IS NULL")

    # (user_id, prompt 名) → system_id:扫该用户各系统 manifest 的引用
    prompt_system = {}
    for uid, slug, manifest in q(cur, "SELECT user_id, slug, manifest FROM systems"):
        m = manifest if isinstance(manifest, dict) else json.loads(manifest)
        refs = {m.get("system_prompt")} | {s.get("prompt")
                                           for s in (m.get("stages") or {}).values()}
        for p in filter(None, refs):
            prompt_system.setdefault((uid, p), slug)

    sys_by_name = {(r[0], r[1]): r[2] for r in q(cur, "SELECT user_id, slug, id FROM systems")}
    distinct = q(cur, "SELECT DISTINCT user_id, name FROM prompt_versions")
    for uid, pname in distinct:
        sslug = prompt_system.get((uid, pname))
        sid = sys_by_name[(uid, sslug)] if sslug and (uid, sslug) in sys_by_name else None
        created = q(cur, "SELECT min(created_at) FROM prompt_versions"
                         " WHERE user_id=%s AND name=%s", (uid, pname))[0][0] or ""
        cur.execute("INSERT INTO prompts(system_id,user_id,slug,display_name,created_at)"
                    " VALUES(%s,%s,%s,%s,%s)",
                    (sid, uid if sid is None else 0, pname, pname, created))
    # 回填 prompt_id(Python 直配,可靠),然后退役旧键列
    cur.execute("ALTER TABLE prompt_versions ADD COLUMN IF NOT EXISTS prompt_id INTEGER")
    # 匹配规则:用户级 prompt(user_id=uid, system_id NULL)优先;
    # 否则找 slug 相同、system_id 属于该用户系统的系统级 prompt
    prows = q(cur, "SELECT id, system_id, user_id, slug FROM prompts ORDER BY id")
    user_systems = {}
    for uid, sid in q(cur, "SELECT user_id, id FROM systems"):
        user_systems.setdefault(uid, set()).add(sid)
    unmatched = 0
    for rid, uid, pname in q(cur, "SELECT id, user_id, name FROM prompt_versions"):
        pid = next((p[0] for p in prows
                    if p[3] == pname and p[1] is None and p[2] == uid), None) \
            or next((p[0] for p in prows
                     if p[3] == pname and p[1] in user_systems.get(uid, set())), None)
        if pid is None:
            unmatched += 1
            continue
        cur.execute("UPDATE prompt_versions SET prompt_id=%s WHERE id=%s", (pid, rid))
    if unmatched:
        print(f"  ⚠ {unmatched} 行 prompt_versions 未匹配 prompt(检查!)")
    cur.execute("ALTER TABLE prompt_versions DROP COLUMN IF EXISTS user_id")
    cur.execute("ALTER TABLE prompt_versions DROP COLUMN IF EXISTS name")
    cur.execute("DROP INDEX IF EXISTS pv_user_name_ver")
    cur.execute("ALTER TABLE prompt_versions ALTER COLUMN prompt_id SET NOT NULL")
    print(f"  prompts: {len(distinct)} 条身份,未匹配 {unmatched}")


def main() -> None:
    check = "--check" in sys.argv
    with psycopg.connect(DSN) as conn:
        cur = conn.cursor()
        print(f"P0 迁移{'体检(--check,不改数据)' if check else '开始'}")
        print("— ⑥ 数据卫生 —");   hygiene(cur, check)
        print("— ①② bags/ledgers → portfolios —"); migrate_portfolios(cur, check)
        print("— ⑤ systems —");    migrate_systems(cur, check)
        print("— ④ runs —");       migrate_runs(cur, check)
        print("— ③ prompts —");    migrate_prompts(cur, check)
        # 验证摘要
        print("— 验证 —")
        for t in ("portfolios", "runs", "systems", "prompts", "prompt_versions",
                  "bags", "ledgers"):
            if table_exists(cur, t):
                n = q(cur, f"SELECT count(*) FROM {t}")[0][0]
                print(f"  {t}: {n} 行")
        n_orphan = q(cur, "SELECT count(*) FROM prompt_versions WHERE prompt_id IS NULL"
                     if col_exists(cur, "prompt_versions", "prompt_id") else "SELECT 0")[0][0]
        print(f"  prompt_versions 未挂 prompt_id: {n_orphan}")
        if check:
            conn.rollback()
            print("体检完成(已回滚,未写库)")
        else:
            conn.commit()
            print("迁移完成(已提交)")


if __name__ == "__main__":
    main()
